### ISSUE TITLE
[Enhancement] LibPandaDNA Support

### ISSUE THREAD

**Issue by NoraHanegan** [OpenToontownTools/OpenLevelEditor#29]
## Description

This is the **Open** Level Editor so maybe support for the Open Source LibDisney could be used.

**Comment by LittleToonCat** [comment]
If you're talking about compiling the levels into libpandadna's .pdna files, that feature's already supported since a4b2085.  Just start the editor with the `--compiler libpandadna` argument.

But for using libpandadna as the base reader instead of libtoontown, that would be an interesting concept but the last time I checked (and attempted such a thing myself before this project's existence), libpandadna is missing some of the code that the level editor needs to be used with.  It might be possible though, but it would probably be very hacky just to support both libtoontown and libpandadna.  Besides, since this project is based out of Disney's own coding, it is more tailor suited for libtoontown anyways.

**Comment by drewc5131** [comment]
### what?????
The Open Source LibDisney? [You mean the repo that is CLEARLY pointed to in the readme as a REQUIREMENT??](https://github.com/OpenToontownTools/libtoontown)

LibPandaDNA is also supported as a compiler.

Do some basic reading before making an issue.
